# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.1
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

# Установим базовые пакеты + PostgreSQL client
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      curl \
      libjemalloc2 \
      libvips \
      postgresql-client \
      build-essential \
      git \
      libyaml-dev \
      pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем bundler
RUN gem install bundler

# Копируем Gemfile и Gemfile.lock
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Копируем весь код приложения
COPY . .

# Создаём пользователя rails для безопасности
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp

USER 1000:1000

EXPOSE 3000

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"]
