services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        RUBY_VERSION: 3.4.1
    container_name: cl_test_assignment_dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:postgres@db:5432/cl_test_assignment_development"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: cl_test_assignment_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cl_test_assignment_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'

volumes:
  db_data:
  bundle: