# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flight_search.proto for package 'proto'

require 'grpc'
require 'flight_search_pb'

module Proto
  module FlightSearchService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.FlightSearchService'

      rpc :SearchRoutes, ::Proto::SearchRequest, ::Proto::SearchResponse
    end

    Stub = Service.rpc_stub_class
  end
end
