# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flight_search.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x13\x66light_search.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n\rSearchRequest\x12\x0f\n\x07\x63\x61rrier\x18\x01 \x01(\t\x12\x13\n\x0borigin_iata\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65stination_iata\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65parture_from\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x65parture_to\x18\x05 \x01(\t\"7\n\x0eSearchResponse\x12%\n\x0bitineraries\x18\x01 \x03(\x0b\x32\x10.proto.Itinerary\"\xc2\x01\n\tItinerary\x12\x13\n\x0borigin_iata\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65stination_iata\x18\x02 \x01(\t\x12\x32\n\x0e\x64\x65parture_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x61rrival_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x08segments\x18\x05 \x03(\x0b\x32\x0e.proto.Segment\"\xb3\x01\n\x07Segment\x12\x0f\n\x07\x63\x61rrier\x18\x01 \x01(\t\x12\x16\n\x0esegment_number\x18\x02 \x01(\t\x12\x13\n\x0borigin_iata\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65stination_iata\x18\x04 \x01(\t\x12\'\n\x03std\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03sta\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2T\n\x13\x46lightSearchService\x12=\n\x0cSearchRoutes\x12\x14.proto.SearchRequest\x1a\x15.proto.SearchResponse\"\x00\x42<Z:github.com/ruuke/flight_booking/flight_search_go/pkg/protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  SearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SearchRequest").msgclass
  SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.SearchResponse").msgclass
  Itinerary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Itinerary").msgclass
  Segment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Segment").msgclass
end
